Added missing abstracts in .bib
mlresearch/v183 pull request #1
Opened 2022-10-13 03:16 UTC by paobranco

2022-10-13 05:03 UTC, lawrennd requested changes
Hi Paula, Once  the proceedings are published, changing the bub file doesn't effect the site, the files in the _posts subdirectory need editing directly. Neil

2022-10-13 13:31 UTC, paobranco commented
Hi Neil. Thank you. I edited the _posts to include the abstracts of the papers.

2022-10-16 19:39 UTC, lawrennd approved these changes
thanks for the work Paula, but I think what you've provided won't compile. The Abstracts need to be quoted if they've got colons inside them, like e.g. 2022-10-08-komrniczak22a.md otherwise they are not valid yaml. 

One trick if you've got these abstracts in your fork, have a look at them. You'll be able to tell if they're not valid yaml because GitHub won't parse them correctly does that make sense?

Here's an article on quoting in Yaml: https://www.yaml.info/learn/quote.html

2022-10-16 19:41 UTC, lawrennd requested changes
thanks for the work Paula, but I think what you've provided won't compile. The Abstracts need to be quoted if they've got colons inside them, like e.g. 2022-10-08-komrniczak22a.md otherwise they are not valid yaml. 

One trick if you've got these abstracts in your fork, have a look at them. You'll be able to tell if they're not valid yaml because GitHub won't parse them correctly does that make sense?

Here's an article on quoting in Yaml: https://www.yaml.info/learn/quote.html

2022-11-01 03:32 UTC, paobranco commented
Hi Neil. I tried to follow your directions and added some changes to the files. Hopefully this will be OK now!

2025-08-27 06:00 UTC, lawrennd commented
Many apologies for letting this slip through the net Paola.

2025-08-27 06:00 UTC, merged